services:
  postgres:
    container_name: user_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_database
    volumes:
      - .storage/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  mongo:
    container_name: message_mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: messages
    restart: unless-stopped
