services:
  postgres:
    container_name: user_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_database
    volumes:
      - .storage/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  mongo:
    container_name: message_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - .storage/mongo:/data/db
    restart: unless-stopped

  redis:
    container_name: user_cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - .storage/redis:/data
    restart: unless-stopped

